### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by johnz0r** [PrestaShop/mailjet#1]
## Sensitive SQL call

/mailjet.php
258 Tools::getValue('tokp') pSQL
272 $tokp['token_presta'] pSQL
1069 $mjc->Data[0]->CampaignSubject pSQL

/classes/Segmentation.php
364 $this->ll(55) add pSQL
369 $this->ll(56) add pSQL
387 $this->ll(57) add pSQL
392 $this->ll(58) add pSQL

/ajax/ajax.php
280 $row[$obj->ll(47)](int)

/ajax/config.php
80 `values ('.pSQL(Tools::getValue('idbase')).',"` => missing quotes, should be `values ("'.pSQL(Tools::getValue('idbase')).'","`
87 idsource missing quotes

/classes/MailJetEvents.php
149 replace `implode(',', $select)` with `implode('`,`', array_map('bqSQL',$select))`
## Unsafe file access

/libraries/Mailjet.Api.class.php:560, 591 $object may inject `/ \ .. .` and lead to sensitive file access or code execution

check `realpath($this->_cache_path.$file)` starts with `realpath($this->_cache_path)`
## Unserialize

unserialize() call on user controlled input may lead to code execution

/mailjet.php:1146
/mailjet.php:1393
/mailjet.php:1507
/classes/Segmentation.php:1218

Replace these seriliaze/unserialize call with json_encode/json_decode
### Smarty

/views/templates/admin/*tpl
All variables in smarty templates aren't escaped, this could lead to XSS, escape all variables, example : 
`$variable` => `$variable|escape`
### php

/ajax/ajax.php 289-454
/ajax/bundlejs_prestashop.php
/ajax/config.php
/classes/Segmentation.php:161 to 181 and 968
/libraries/Mailjet.Api.class.php 

All outputed variables aren't escaped, they should be escaped with Tools::safeOutput, specially when they come from database, examples : 

`'<ul id="plugproduct'.Tools::getValue('id').'">'` => `'<ul id="plugproduct'.Tools::safeOutput(Tools::getValue('id')).'">'`

```
foreach ($header as $h)
    $content .= '<th>'.$h.'</th>';
```

=>

```
foreach ($header as $h)
    $content .= '<th>'.Tools::safeOutput($h).'</th>';
```

/callback_signup.php
/callback_campaign.php
/callback.php
/ajax.php
/ajax/ajax.php

Every time a page output JSON only data, please add an header('Content-Type: application/json');

In your case you can't just add the header('Content-Type: application/json'); in top of the page because there are mixed output (sometimes HTML only, sometime JSON only)

example : 

```
header('Content-Type: application/json');
die($obj->loadFilter(Tools::getValue('idfilter')));
```
## Unauthorized log file access

/logs/ajax.log there is no access control on /logs/ajax.log, this file may contains sensitive data

**Comment by ddxb** [comment]
Thomas, we need to adjust a few FR and EN  language text issues in the
module today before pushing into final production. Will keep you posted
when done.

--
Stephen Bauer
Head of Business Development
Tel: +33184178951
Mob: ​+33643075510
stephen@mailjet.com
Skype & Twitter: sp_bauer
