### ISSUE TITLE
Doesn't work with v0.1 of MailJet API

### ISSUE THREAD

**Issue by PrestaEdit** [PrestaShop/mailjet#7]

**Comment by ddxb** [comment]
Hi PrestaEdit,

That's correct, this version of the Official Mailjet PrestaShop plugin is compatible with our v3 API to make sure that PrestaShop merchants are able to leverage the advanced segmentation, contact management, our drag-and-drop Newsletter tool, advanced statistics and of course our new ROI statistic that allows merchants to see how many sales their individual marketing campaigns generate.  

Our v1 compatible plugin is still available at https://www.mailjet.com/plugin/prestashop.htm or https://github.com/mailjet/prestashop-mailjet-plugin

Should any v1 user wish to use our v3 compatible plugin, please don't hesitate to contact our Support Team to get your account migrated via https://www.mailjet.com/support/ticket

Regards, 

Mailjet

**Comment by PrestaEdit** [comment]
Hi @ddxb ,

Thanks for feedback ! :)

And thanks for the support ticket tips, I will do... Last time, we said to me to just wait. There is sometimes ;-)

Regards,
J. Danse.

**Comment by PrestaEdit** [comment]
As this brand new module is set up to be compatible with v3 exclusively, I close this issue ;-)
